import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../global.css";
import { Providers } from "@/globalRedux/provider";
import Navbar from "./components/navbar";
import Sidebar from "./components/sidebar";
import Menu from "./components/menu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Gu-Tix - Admin ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="mytheme">
      <body className={inter.className}>
        <Providers>
          <div className="drawer">
            <input id="my-drawer" type="checkbox" className="drawer-toggle" />
            <div className="drawer-content">
              <Navbar />
              <div className="flex pt-16">
                <Sidebar />
                <div className="lg:w-10/12 w-full ms-auto bg-base-200 min-h-screen">
                  {children}
                </div>
              </div>
            </div>
            <div className="drawer-side">
              <label
                htmlFor="my-drawer"
                aria-label="close sidebar"
                className="drawer-overlay"
              ></label>
              <ul className="menu p-4 w-80 min-h-full bg-base-200 text-base-content">
                <Menu />
              </ul>
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
